### ISSUE TITLE
Gcc compilation issue with poky - Yocto

### ISSUE THREAD

**Issue by rohanjuneja** [Green-Mod/poky-container#1] opened 2022-02-15 06:39 UTC
I am compiling a tool from Renesas, which internally compiles gcc. This is failing for me with the error mentioned below, could you please help me with this?

```
| 	lto/lto-lang.o lto/lto.o lto/lto-object.o attribs.o lto/lto-partition.o lto/lto-symtab.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a  -lmpc -lmpfr -lgmp -rdynamic -ldl  -lz libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: fold-const.o: in function `fold_ternary_loc(unsigned int, tree_code, tree_node*, tree_node*, tree_node*, tree_node*)':
| fold-const.c:(.text+0xb963): undefined reference to `generic_simplify(unsigned int, tree_code, tree_node*, tree_node*, tree_node*, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: fold-const.c:(.text+0xba7b): undefined reference to `generic_simplify(unsigned int, tree_code, tree_node*, tree_node*, tree_node*, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: fold-const.o: in function `fold_binary_loc(unsigned int, tree_code, tree_node*, tree_node*, tree_node*)':
| fold-const.c:(.text+0xe04a): undefined reference to `generic_simplify(unsigned int, tree_code, tree_node*, tree_node*, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: fold-const.o: in function `fold_unary_loc(unsigned int, tree_code, tree_node*, tree_node*)':
| fold-const.c:(.text+0x152fa): undefined reference to `generic_simplify(unsigned int, tree_code, tree_node*, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_fold_stmt_to_constant_1(gimple*, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))':
| gimple-fold.c:(.text+0x4aaa): undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.c:(.text+0x4c83): undefined reference to `mprts_hook'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*)':
| gimple-fold.c:(.text+0x5ef3): undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*, tree_node*)':
| gimple-fold.c:(.text+0x5fab): undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_build(gimple**, unsigned int, tree_code, tree_node*, tree_node*, tree_node*, tree_node*)':
| gimple-fold.c:(.text+0x604d): undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*)':
| gimple-fold.c:(.text+0x6111): undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*, tree_node*)':
| gimple-fold.c:(.text+0x61d9): undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `gimple_build(gimple**, unsigned int, built_in_function, tree_node*, tree_node*, tree_node*, tree_node*)':
| gimple-fold.c:(.text+0x62bd): undefined reference to `gimple_simplify(built_in_function, tree_node*, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.o: in function `fold_stmt_1(gimple_stmt_iterator*, bool, tree_node* (*)(tree_node*))':
| gimple-fold.c:(.text+0xc04d): undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.c:(.text+0xce60): undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.c:(.text+0xcfd1): undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: gimple-fold.c:(.text+0xd84c): undefined reference to `maybe_build_generic_op(tree_code, tree_node*, tree_node**)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-cfgcleanup.o: in function `cleanup_control_flow_bb(basic_block_def*)':
| tree-cfgcleanup.c:(.text+0x130b): undefined reference to `gimple_simplify(gimple*, code_helper*, tree_node**, gimple**, tree_node* (*)(tree_node*), tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.o: in function `vn_nary_build_or_lookup_1(code_helper, tree_node*, tree_node**, bool)':
| tree-ssa-sccvn.c:(.text+0x9373): undefined reference to `mprts_hook'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0x9396): undefined reference to `mprts_hook'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0x93fc): undefined reference to `maybe_push_res_to_seq(code_helper, tree_node*, tree_node**, gimple**, tree_node*)'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0x9554): undefined reference to `gimple_resimplify1(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0x955b): undefined reference to `mprts_hook'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0x95c4): undefined reference to `gimple_resimplify3(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0x95e4): undefined reference to `gimple_resimplify2(gimple**, code_helper*, tree_node*, tree_node**, tree_node* (*)(tree_node*))'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.o: in function `visit_use(tree_node*)':
| tree-ssa-sccvn.c:(.text+0xbceb): undefined reference to `mprts_hook'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.c:(.text+0xbcfe): undefined reference to `mprts_hook'
| /home/renesas/Desktop/workspace/build/tmp/hosttools/ld: tree-ssa-sccvn.o: in function `sccvn_dom_walker::before_dom_children(basic_block_def*)':
| tree-ssa-sccvn.c:(.text+0xeb63): undefined reference to `gimple_simplify(tree_code, tree_node*, tree_node*, tree_node*, gimple**, tree_node* (*)(tree_node*))'
| collect2: error: ld returned 1 exit status
| make[1]: *** [../../../../../../../work-shared/gcc-8.3.0-r0/gcc-8-8.3.0/src/gcc/lto/Make-lang.in:81: lto1] Error 1
| make[1]: *** Waiting for unfinished jobs....
| make[1]: Leaving directory '/home/renesas/Desktop/workspace/build/tmp/work/x86_64-linux/gcc-crosssdk-x86_64-pokysdk-linux/8.3.0-r0/gcc-8.3.0/build.x86_64-linux.x86_64-pokysdk-linux/gcc'
| make: *** [Makefile:4315: all-gcc] Error 2
| WARNING: exit code 1 from a shell command.
| 
ERROR: Task (/home/renesas/Desktop/workspace/build/../meta-rzv/recipes-debian/gcc/gcc-crosssdk_debian.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4697 tasks of which 4694 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/renesas/Desktop/workspace/build/../meta-rzv/recipes-debian/gcc/gcc-crosssdk_debian.bb:do_compile
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
```

**Comment by GiorgioBertolotti** [comment] 2022-02-15 07:24
Hello @rohanjuneja, could you please provide more context about this?
Like which tool are you trying to compile, which command is producing this error and stuff like this.
Also did you follow the instructions in the README to setup the Docker container correctly?
Thanks and have a nice day!

**Comment by rohanjuneja** [comment] 2022-02-15 09:21
Hello @GiorgioBertolotti, thanks for your response. I am basically compiling the Linux package and corresponding SDK of Renesas from the link below. 
[Linux Support Package](https://www.renesas.com/us/en/document/rln/rzv2l-linux-package-version-100-release-note?language=en&r=1496691)
Here the build passes properly while compiling Linux from Section 3.1 (am executing 'bitbake core-image-weston'). But it fails while building SDK as per Section 3.2 ('bitbake core-image-weston -c populate_sdk').
After searching a bit about this, it seems that the gcc compilation is being failed here.

I have attached the complete log files for your reference
[error_file.txt](https://github.com/Green-Mod/poky-container/files/8067616/error_file.txt)
[log_file.txt](https://github.com/Green-Mod/poky-container/files/8067617/log_file.txt).

**Comment by GiorgioBertolotti** [comment] 2022-02-15 09:57
Hi @rohanjuneja, thank you for the additional info!
This repo has the purpose to provide a Docker environment that you can use to build your yocto images, so if the step 3.1 of the guide you linked is working correctly, the Docker environment is doing his job.

The only thing I can tell you to try to help you is that I recently run in a similar problem:
```
ERROR: m4-native-1.4.18-r0 do_compile: oe_runmake failed
```

And I've just found out that there was a [patch](https://stackoverflow.com/questions/67500482/petalinux-project-build-failing-with-m4-native-1-4-18-r0-do-compile-failed-on-ho) for it, try to look around if someone had your same problem.

I'm closing the issue because it is not related to the repo, but if you need support with Yocto you can email me and I'll try to help :)

**Closed as completed by GiorgioBertolotti** 2022-02-15 09:57 UTC

**Comment by rohanjuneja** [comment] 2022-02-15 15:03
Hi @GiorgioBertolotti Thanks for the detailed response!
Could you please confirm if the error is because of the gcc compilation, as I can understand from the log file?

Sure, I will try the patch out. And also will try to get in touch with Renesas too.
Thanks!

**Comment by GiorgioBertolotti** [comment] 2022-02-15 15:18
Hi @rohanjuneja, yes I can confirm it is a gcc compilation problem.

I'd like to point out that the problem may also be related to a compatibility issue due to the Dockerfile's Ubuntu version (which is set to be 20.04), which may cause problems with some Yocto Project versions.

You could try to set the Dockerfile's Ubuntu version to an older release (like 18.04) and see if it works.

Good luck fixing the error and have a nice day :)
